<?php

/**
 * @file
 * Module file for Open Data Canada module.
 *
 * This module defines a Drupal content node that mirrors the
 * packages in CKAN. Instead of querying CKAN directly, basic package
 * information is stored in the table od_package.
 */

/**
 * Implements hook_menu().
 *
 * 
 */
function od_package_menu() {
  $items['dataset/%'] = array(
    'page callback' => '_od_package_page',
    'access arguments' => array('access content'),
    'title' => 'Dataset',
    'page arguments' => array(1),
  );
  return $items;
}

/**
 * Implements hook_node_info().
 *
 * We use hook_node_info() to define our node content type.
 */
function od_package_node_info() {
  // We define the node type as an associative array.
  return array(
    'od_package' => array(
      'name' => t('Canada Open Data Node Type'),
      // 'base' tells Drupal the base string for hook functions.
      // This is often the module name; if base is set to 'mymodule',
      // Drupal would call mymodule_insert() or similar for node
      // hooks. In our case, the base is 'od_package'.
      'base' => 'od_package',
      'description' => t('This node links to a CKAN Dataset.'),
      'title_label' => t('Package name'),
      // We'll set the 'locked' attribute to TRUE, so users won't be
      // able to change the machine name of our content type.
      'locked' => TRUE,
    ),
  );
}

/**
 * Implement hook_form().
 *
 * Drupal needs for us to provide a form that lets the user
 * add content. This is the form that the user will see if
 * they go to node/add/od_package.
 */
function od_package_form($node, $form_state) {
  return node_content_form($node, $form_state);
}

function _od_package_page($arg1 = NULL) {
  global $user;
  global $language;
  
  /* Check the package table to determine if the requested package exists.
   * If it does not, then return an error message. If it does exist then 
   * determine if a node has been previously associated with the package.
   * If one has, then return the node.
   * 
   * If no node has been associated with the package, then create the node, and
   * associate it with the package.
   */
   
   if ( is_null($arg1) ) {
        // We will just show a standard "access denied" page in this case.
        drupal_access_denied();
        return;  // We actually don't get here.
    }
   $renderable_array = array();
   
   // Retrieve info from package. If it exists, only one record will be returned
   $result = db_select('od_package', 'c')
    ->fields('c', array('pkg_node_id', 'pkg_id', 'pkg_name', 'pkg_title_en', 
        'pkg_title_fr', 'pkg_description_en', 'pkg_description_fr'))
    ->condition('pkg_name', $arg1, '=')
    ->execute();
    
    if ($result->rowCount() == 1) { // package exists
        $record = $result->fetchAssoc();
        $nid = $record['pkg_node_id'];
        $node = NULL;
        if ($nid != 0) { // node already exists - use it
            $node = node_load($nid);
        } else { // need to create a node
 
            $node = new stdClass();
            $node->type = 'od_package';
            
            // Should use a translateable field as a title
            $node->title = $record['pkg_title_en'];
            node_object_prepare($node);
            $node->language = $language->language; 
            $node->uid = $user->uid;
            $node->comment = 2;
            $node->path['alias'] = 'dataset/' . $record['pkg_name'];
            $node = node_submit($node);
            node_save($node);
            
            // Save the node ID to OD_PACKAGE
            $record['pkg_node_id'] = $node->nid;
            $count = db_update('od_package')
              ->fields($record)
              ->condition('pkg_name', $record['pkg_name'], '=')
              ->execute();
        }
        // Generate the output for the node.
       $renderable_array['node_list'][] = node_view($node);
       $display_desc = '';
       $display_title = '';
       if ($language->language == 'en') {
         $display_desc = $record['pkg_description_en'];
         $display_title = $record['pkg_title_en'];
       } else {
         $display_desc = $record['pkg_description_fr'];
         $display_title = $record['pkg_title_fr'];
       }
       $renderable_array['description'] = array(
         '#type' => 'markup',
         '#markup' => '<div>' . $display_desc . '</div>',
       );
       
    } else { // package does not exist - just return an error
      drupal_set_message(t('This dataset does not exist.'), 'warning');
    };
    return $renderable_array;       

}